### ISSUE TITLE
 semantic segmentation  pruning

### ISSUE THREAD

**Issue by 972461099** [MingSun-Tse/Regularization-Pruning#1]
hi,thanks your nice work,

Can the pruning method be applied to the semantic segmentation model?

**Comment by MingSun-Tse** [comment]
Hi @972461099 , thanks for your interest in our work! We didn't evaluate our method on semantic segmentation models in our paper, but in general, the proposed methods are _generic_ DNN pruning approaches, so yes, they can be applied to semantic segmentation models.

**Comment by 972461099** [comment]
thankx,I will try
