### ISSUE TITLE
Unable to reproduce the reported CIFAR results

### ISSUE THREAD

**Issue by Noktyrn** [MingSun-Tse/Regularization-Pruning#2]
Hi, I was interested in your article and tried to prune resnet56 and vgg19 models trained on cifar10/cifar100 datasets, but I couldn't get the same results as you got. All the parameters were taken from the appendix of the article, but probably I've missed something. Can you tell me please what am I doing wrong?

My results are:

1. vgg19: 61.62 with L1, 64.81 with GReg-1 and 62.86 with GReg-2, the baseline value from the article is 67.56
2. resnet56:  88.17 with L1, 90.5 with GReg-1 and 90.9 with GReg-2, the baseline value from the article is 93.36

I've launched the pipeline with following configs:

1. For vgg19: CUDA_VISIBLE_DEVICES=0,1 python main.py --dataset cifar100 --arch vgg19 --pretrained --method GReg-1 --screen --stage_pr [0:00,1-15:0.7] --project G1__vgg19__0.7__new --update_reg_interval 10 --stabilize_reg_interval 5000 --lr_ft 0:0.01,60:0.001,90:0.0001 --batch_size_prune 256 --epochs 120 --wd 5e-4

2. For resnet56: CUDA_VISIBLE_DEVICES=0,1 python main.py --dataset cifar10 --arch resnet56 --pretrained --method GReg-2 --screen --stage_pr [0,0.75,0.75,0.32,0] --project G2__resnet56__new --update_reg_interval 10 --stabilize_reg_interval 5000 --lr_ft 0:0.01,60:0.001,90:0.0001 --batch_size_prune 256 --epochs 120 --wd 5e-4

**Comment by MingSun-Tse** [comment]
Hi @Noktyrn , thanks for your interest in our work! I guess the main problem is that you train from scratch instead of pruning a _trained_ model. Sorry we did not make it clear. I've updated the REAME.md. Please follow the README and try again. Let me know if you have further questions. Regards,

**Comment by Noktyrn** [comment]
Hi @MingSun-Tse! Thanks a lot for your help, now everything works.

Best regards
