### ISSUE TITLE
运行时遇到问题

### ISSUE THREAD

**Issue by linklist2** [MingSun-Tse/Regularization-Pruning#5]
![image](https://user-images.githubusercontent.com/46252413/157453193-0e145fa9-a517-4428-8cc4-0cd2e754a688.png)
运行时一直很长一段时间都是cd XXX, python main.py...
![image](https://user-images.githubusercontent.com/46252413/157458113-a7ac853a-3f94-438d-b295-08c69d2505c2.png)

然后会在目录里一直生成这些log文件，请问我该如何关闭这些东西，直接运行呢？

**Comment by MingSun-Tse** [comment]
`cd ...` 和`python main.py`这些东西都是logging的部分, 为了将来potentially可能要重复实验. 目前这个code没提供关掉这代码的功能. 那些log文件夹不能关掉, 因为log txt和checkpoints户会保留在其中. 

"一直很长一段时间都是cd XXX, python main.py" -- 这个我不太能理解, 会有多长时间卡在这里?

**Comment by linklist2** [comment]
> `cd ...` 和`python main.py`这些东西都是logging的部分, 为了将来potentially可能要重复实验. 目前这个code没提供关掉这代码的功能. 那些log文件夹不能关掉, 因为log txt和checkpoints户会保留在其中.
> 
> "一直很长一段时间都是cd XXX, python main.py" -- 这个我不太能理解, 会有多长时间卡在这里?

就有的时候是一直卡着，有的时候是半分钟左右吧，然后主要是运行一个epoch，我目录里就出现好多个log文件，我感觉运行完160epochs可能得有上百个文件夹了

**Comment by linklist2** [comment]
> `cd ...` 和`python main.py`这些东西都是logging的部分, 为了将来potentially可能要重复实验. 目前这个code没提供关掉这代码的功能. 那些log文件夹不能关掉, 因为log txt和checkpoints户会保留在其中.
> 
> "一直很长一段时间都是cd XXX, python main.py" -- 这个我不太能理解, 会有多长时间卡在这里?

是因为使用的win10的原因吗？

**Comment by linklist2** [comment]
> `cd ...` 和`python main.py`这些东西都是logging的部分, 为了将来potentially可能要重复实验. 目前这个code没提供关掉这代码的功能. 那些log文件夹不能关掉, 因为log txt和checkpoints户会保留在其中.
> 
> "一直很长一段时间都是cd XXX, python main.py" -- 这个我不太能理解, 会有多长时间卡在这里?

另外，似乎每一个log文件夹都把整个项目缓存了一遍。
![image](https://user-images.githubusercontent.com/46252413/157466161-790a6c8b-865a-4e38-866e-b1d75ddfef7b.png)

**Comment by MingSun-Tse** [comment]
你好, 我刚又在我的机子上测试了一下, 没有出现这些问题. 我的环境: Ubuntu1604. Pytorch1.3.1
每个log dir中把所有.py code存一遍是正常的, code里面确实是这么写的. 
Win10上我没测过, 很可能是这个原因. 如果你能找到linux的机器, 推荐使用linux的机器

**Comment by linklist2** [comment]
> 你好, 我刚又在我的机子上测试了一下, 没有出现这些问题. 我的环境: Ubuntu1604. Pytorch1.3.1 每个log dir中把所有.py code存一遍是正常的, code里面确实是这么写的. Win10上我没测过, 很可能是这个原因. 如果你能找到linux的机器, 推荐使用linux的机器

非常感谢，我会尝试的。

**Comment by linklist2** [comment]
> 你好, 我刚又在我的机子上测试了一下, 没有出现这些问题. 我的环境: Ubuntu1604. Pytorch1.3.1 每个log dir中把所有.py code存一遍是正常的, code里面确实是这么写的. Win10上我没测过, 很可能是这个原因. 如果你能找到linux的机器, 推荐使用linux的机器

您好，我今天在ubuntu的机器上试了一下，确实没有再出现很多个log文件的问题了

**Comment by linklist2** [comment]
> 你好, 我刚又在我的机子上测试了一下, 没有出现这些问题. 我的环境: Ubuntu1604. Pytorch1.3.1 每个log dir中把所有.py code存一遍是正常的, code里面确实是这么写的. Win10上我没测过, 很可能是这个原因. 如果你能找到linux的机器, 推荐使用linux的机器


您好，我今天在ubuntu的机器上试了一下，确实没有再出现很多个log文件的问题了

**Comment by MingSun-Tse** [comment]
好的, 谢谢, 有空我查一下这个windows上的bug, 应该是跟我写的smielogging的包有关系. 感谢您的反馈!
